//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Readiculous.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Readiculous.Resources.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book already exists!.
        /// </summary>
        public static string BookExists {
            get {
                return ResourceManager.GetString("BookExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book does not exist!.
        /// </summary>
        public static string BookNotExists {
            get {
                return ResourceManager.GetString("BookNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book with the same title and author already exists!.
        /// </summary>
        public static string BookTitleAndAuthorExists {
            get {
                return ResourceManager.GetString("BookTitleAndAuthorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists!.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not exist!.
        /// </summary>
        public static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book already favorited!.
        /// </summary>
        public static string FavoriteBookExists {
            get {
                return ResourceManager.GetString("FavoriteBookExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book not favorited!.
        /// </summary>
        public static string FavoritedBookNotExists {
            get {
                return ResourceManager.GetString("FavoritedBookNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found or failed to send OTP..
        /// </summary>
        public static string ForgotPasswordEmailFailed {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre Name already exists!.
        /// </summary>
        public static string GenreExists {
            get {
                return ResourceManager.GetString("GenreExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre does not exist!.
        /// </summary>
        public static string GenreNotExist {
            get {
                return ResourceManager.GetString("GenreNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image failed to delete!.
        /// </summary>
        public static string ImageFailedToDelete {
            get {
                return ResourceManager.GetString("ImageFailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image failed to upload!.
        /// </summary>
        public static string ImageFailedToUpload {
            get {
                return ResourceManager.GetString("ImageFailedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email or Password!.
        /// </summary>
        public static string IncorrectLoginCredentials {
            get {
                return ResourceManager.GetString("IncorrectLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password does not match your current password!.
        /// </summary>
        public static string InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book with the same ISBN already exists!.
        /// </summary>
        public static string ISBNExists {
            get {
                return ResourceManager.GetString("ISBNExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review already exists for this book by the user!.
        /// </summary>
        public static string ReviewExists {
            get {
                return ResourceManager.GetString("ReviewExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review does not exist for this book by the user!.
        /// </summary>
        public static string ReviewNotExist {
            get {
                return ResourceManager.GetString("ReviewNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error occured!.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Update Favorite: .
        /// </summary>
        public static string UnableToAddFavorite {
            get {
                return ResourceManager.GetString("UnableToAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot delete self!.
        /// </summary>
        public static string UserCannotDeleteSelf {
            get {
                return ResourceManager.GetString("UserCannotDeleteSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId already exists!.
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists!.
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username does not exist!.
        /// </summary>
        public static string UsernameNotExist {
            get {
                return ResourceManager.GetString("UsernameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not found!.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
